/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Desktop(props) {
  const modelPath = `${import.meta.env.BASE_URL}models/Desktop.glb`
  const { nodes, materials } = useGLTF(modelPath)
  const { isMobile, ...groupProps } = props
  const scale = isMobile ? 0.8 : 2
  const toto = useRef()
  const baseY = useRef(null)

  useFrame(({ clock }) => {
  if (!toto.current) return

  // On capture UNE SEULE FOIS la position initiale
  if (baseY.current === null) {
    baseY.current = toto.current.position.x
  }

  const t = clock.getElapsedTime()

  toto.current.position.x =
    baseY.current +
    Math.sin(t * 4) * Math.max(0, Math.sin(t * 0.5)) * 0.015
})

  return (
    <group {...props} dispose={null} scale={scale} rotation={[0.5, -1.2, 0.3]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.011']}
        position={[0.775, 0.54, 0.521]}
        rotation={[-1.629, -1.123, 3.108]}
        scale={[0.049, 0.02, 0.049]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Clavier.geometry}
        material={materials['Material.007']}
        position={[-0.006, 0.784, 0.13]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.313, -0.007, -0.153]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Souris.geometry}
        material={materials['Material.008']}
        position={[0.447, 0.784, 0.13]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.046, -0.007, -0.072]}
      />
      <group
        position={[0, 0.752, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.02, -0.475]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials['Material.003']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Material.005']}
        position={[-0.368, 0.779, -0.318]}
        scale={[0.062, 0.004, 0.065]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.006']}
        position={[-0.361, 0.779, -0.266]}
        scale={[0.195, 0.006, 0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ecran.geometry}
        material={materials['Material.004']}
        position={[-0.347, 1.121, -0.239]}
        rotation={[0, 0.221, 0]}
        scale={[0.436, 0.252, 0.011]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials['Material.014']}
        position={[0.489, 0.779, -0.266]}
        scale={[0.195, 0.006, 0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ecran001.geometry}
        material={materials['Material.012']}
        position={[0.51, 1.121, -0.194]}
        rotation={[0, -0.317, 0]}
        scale={[0.436, 0.252, 0.011]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials['Material.013']}
        position={[0.509, 0.779, -0.295]}
        rotation={[0, -0.243, 0]}
        scale={[0.062, 0.004, 0.065]}
      />
      <group position={[-0.566, 1.815, -0.542]} rotation={[0.053, 0.026, -0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials['Material.016']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_2.geometry}
          material={materials['Material.017']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials['Material.018']}
        position={[0.242, 1.845, -0.547]}
        rotation={[1.792, -1.473, -2.902]}
        scale={[-0.137, -0.005, -0.18]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.010']}
        position={[-0.86, 1.525, -0.56]}
        scale={[-0.041, -0.007, -0.036]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['Material.009']}
        position={[-0.963, 1.494, -0.553]}
        scale={[0.158, 0.028, 0.103]}
      />
      <mesh
        ref={toto}
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials['Material.015']}
        position={[-1.019, 1.527, -0.56]}
        scale={[-0.062, -0.011, -0.055]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['Material.001']}
        position={[-0.487, 0.775, 0.196]}
        rotation={[0, -0.206, 0]}
        scale={[-0.096, 0, -0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['Material.002']}
        position={[-0.781, 0.776, 0.302]}
        rotation={[0, 0.78, 0]}
        scale={[-0.096, 0, -0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials['Material.019']}
        position={[-0.765, 0.776, 0.196]}
        rotation={[0, 0.21, 0]}
        scale={[-0.096, 0, -0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Material.020']}
        position={[-0.607, 0.776, 0.244]}
        rotation={[0, 0.21, 0]}
        scale={[-0.096, 0, -0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials['Material.021']}
        position={[-0.068, 1.807, -0.553]}
        rotation={[1.555, 0, 0]}
        scale={[0.567, 0.028, 0.268]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials['Material.022']}
        position={[0.748, 0.815, 0.063]}
        scale={0.042}
      />
      <group
        position={[0.736, 0.822, 0.047]}
        rotation={[0.108, -0.563, 0.542]}
        scale={[-0.003, -0.044, -0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials['Material.024']}
        />
      </group>
      <group
        position={[0.748, 0.822, 0.037]}
        rotation={[-0.342, 0, 0]}
        scale={[-0.003, -0.044, -0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016.geometry}
          material={materials['Material.026']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_1.geometry}
          material={materials['Material.025']}
        />
      </group>
      <group
        position={[0.772, 0.833, 0.045]}
        rotation={[-0.425, 0, 0]}
        scale={[-0.003, -0.044, -0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017.geometry}
          material={materials['Material.028']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_1.geometry}
          material={materials['Material.027']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials['Material.031']}
        position={[-0.874, -0.078, 0.734]}
        rotation={[Math.PI, -0.98, Math.PI]}
        scale={[0.126, 0.029, 0.098]}
      />
    </group>
  )
}

useGLTF.preload('/models/Desktop.glb')